### ISSUE TITLE
V3.3 Colorpicker error's in console

### ISSUE THREAD

**Issue by NTFSquad** [AlexR32/Bracket#1]
Line 1447 fixed by just tostringing the bool:

PaletteAsset.Alpha.Value.Text = tostring(Value[4])

**Comment by AlexR32** [comment]
Value[4] is not the bool its actually alpha value of HSV
you should not use bool on value[4], if you need rainbow mode set value[5] to true

**Comment by NTFSquad** [comment]
Ma bad i switched to v3.4 now. by the way question is there a way to use the section's name instead  not the toggle's in the keybind list?

**Comment by AlexR32** [comment]
> is there a way to use the section's name instead not the toggle's in the keybind list?

No, and i dont see any reason why you need that but i might add custom name option for keybind list

**Comment by NTFSquad** [comment]
That would be great thank you, the reason i requested that is because currently i use Section for every feature and the toggle for them is named Enabled.

**Comment by AlexR32** [comment]
Added `Keybind.CustomName` in https://github.com/AlexR32/Bracket/commit/34b645e5769e31702b9b81c8f73a6dcd9ada5b16

**Comment by NTFSquad** [comment]
## Hello AlexR32, i would like to ask some questions about V3.4.

Firstly is the tab button is there a way to make like in V3? here's what i mean

> ![image](https://github.com/user-attachments/assets/e02aa55b-cfee-41fd-bcf0-dc79d432d458)

Secondly do you plan to add keybind types?

> **Toggle / Hold**

Lastly how's your day?

> **Hope it's great.**

**Comment by AlexR32** [comment]
> Secondly do you plan to add keybind types?

I don't know how to implement this, I find it hard to understand how to do this, should there be a button to toggle this state? Or should just right-clicking on the key text toggle the state? Then if it is a click, how to inform the user about the state change, should it be a tool tip or additional text?

> Firstly is the tab button is there a way to make like in V3? here's what i mean

At this time this style of tab buttons is not available but I can make it

**Comment by NTFSquad** [comment]
> Secondly do you plan to add keybind types?

Honestly same but by my opinion you should right-click on the key text toggle to change the state.

and the informing part either a tool tip OR highlighting the current state here's what i mean

![image](https://github.com/user-attachments/assets/afb0f965-ba3b-46a6-be16-da6382502d4e)

> Firstly is the tab button is there a way to make like in V3? here's what i mean

I will be waiting!

> Edit

From the image the always state shouldn't be an option just the keybind being unbinded should be the state of always

**Comment by NTFSquad** [comment]
> Window.Blur Bug


Basicly using Window.Blur at the startup will not work but later on will (like using a toggle after)

```lua
local Bracket = loadstring(game:HttpGet("https://raw.githubusercontent.com/AlexR32/Bracket/main/BracketV34.lua"))()

local Window = Bracket:Window({Blur = true}) do
	print(Window.Blur)
end
```

![image](https://github.com/user-attachments/assets/b5fc8a78-785d-4041-bd6b-eb3f96c3a8de)

> Edit

I haven't tested on other version's only V3.4

**Comment by AlexR32** [comment]
Everything you suggested and reported is added/fixed in new commit: https://github.com/AlexR32/Bracket/commit/ad2b7dfc00f6f2905722c694606986220ca3122f

Thanks for your contributions
Edit: make sure open new issue for other things because this issue topic becomes complete mess

**Comment by NTFSquad** [comment]
> Window.Name Bug

Basicly changing Window.Name at any point after the Window function will not work it will just error

```lua
local Bracket = loadstring(game:HttpGet("https://raw.githubusercontent.com/AlexR32/Bracket/main/BracketV34.lua"))()

local Window = Bracket:Window({Name = "Project Noir"}) do
    Window.Name = "Example"
end
```


![image](https://github.com/user-attachments/assets/e6569c3c-6d1e-45ee-9e2c-d92b7435cc7d)
