### ISSUE TITLE
Window.Name

### ISSUE THREAD

**Issue by NTFSquad** [AlexR32/Bracket#2]
> make sure open new issue for other things because this issue topic becomes complete mess

**Am i blind? hell ye man** anyways here ya go

> Window.Name Bug

Basicly changing Window.Name at any point after the Window function will not work it will just error

```lua
local Bracket = loadstring(game:HttpGet("https://raw.githubusercontent.com/AlexR32/Bracket/main/BracketV34.lua"))()

local Window = Bracket:Window({Name = "Project Noir"}) do
    Window.Name = "Example"
end
```

![image](https://github.com/user-attachments/assets/e6569c3c-6d1e-45ee-9e2c-d92b7435cc7d)

> Edit

The location of the title just changed if i remember correctly from yesterday when i used dex it wasn't in Topbar before [(Line 2479)](https://github.com/AlexR32/Bracket/blob/ad2b7dfc00f6f2905722c694606986220ca3122f/BracketV34.lua#L2479)

![image](https://github.com/user-attachments/assets/74781504-570a-446d-8ec9-01006171f0b4)

**Comment by NTFSquad** [comment]
> Bracket:Push Bug

Bracket:Push will break it will just error and the notification will stay forever [(Line 4383)](https://github.com/AlexR32/Bracket/blob/ad2b7dfc00f6f2905722c694606986220ca3122f/BracketV34.lua#L4383)

```lua
local Bracket = loadstring(game:HttpGet("https://raw.githubusercontent.com/AlexR32/Bracket/main/BracketV34.lua"))()

local Window = Bracket:Window({Name = "Project Noir"}) do
    Bracket:Push({
        Title = "Other Title",
        Description = "Other Description"
    })
end
```

![image](https://github.com/user-attachments/assets/b05d7644-acbe-41fd-8088-9ee1209effa5)
![image](https://github.com/user-attachments/assets/ce5b4089-aba0-4e5e-94e4-083f9b8053d2)

> Bracket:Toast Bug

Bracket:Toast will break it will just error and the notification will stay forever [(Line 4423)](https://github.com/AlexR32/Bracket/blob/ad2b7dfc00f6f2905722c694606986220ca3122f/BracketV34.lua#L4423)

```lua
local Bracket = loadstring(game:HttpGet("https://raw.githubusercontent.com/AlexR32/Bracket/main/BracketV34.lua"))()

local Window = Bracket:Window({Name = "Project Noir"}) do
    Bracket:Toast({
        Title = "Other Title"
    })
end
```

![image](https://github.com/user-attachments/assets/da6bd6d6-8b1f-43a0-a0ab-18d02c17c2f6)
![image](https://github.com/user-attachments/assets/f22054cc-d4f3-42a6-92ce-4640d053abe4)

**Comment by AlexR32** [comment]
Thanks for finding these bugs its fixed in https://github.com/AlexR32/Bracket/commit/f2089bcfbb198f84a7ba5cc8287d0ecf662cba6a
and your #3 issue is also fixed
