### ISSUE TITLE
KeybindList.Title

### ISSUE THREAD

**Issue by NTFSquad** [AlexR32/Bracket#4]
> KeybindList.Title Bug

Basicly trying to use KeybindList.Title on the already created KeybindList will not work it will just error [(Line 2595)](https://github.com/AlexR32/Bracket/blob/f2089bcfbb198f84a7ba5cc8287d0ecf662cba6a/BracketV34.lua#L2595)

```lua
local Bracket = loadstring(game:HttpGet("https://raw.githubusercontent.com/AlexR32/Bracket/main/BracketV34.lua"))()

local Window = Bracket:Window({Name = "Project Noir"}) do
    local KeybindList = Window:KeybindList({Enabled = true})

    KeybindList.Title = "Other Keybinds"
end
```

![image](https://github.com/user-attachments/assets/d90752d3-31b6-4523-a694-791a55a18f2f)
![image](https://github.com/user-attachments/assets/8d425c62-de28-4f78-ac01-7e96cf4ecd4a)

Remain's the default title

![image](https://github.com/user-attachments/assets/7536d3eb-c62e-44af-ad64-b91269a23a41)

**Comment by NTFSquad** [comment]
Also could it be possible to enable RichText for the Watermark? i am doing it manually right now, the reason being for a cool colored watermark [(Line 356)](https://github.com/AlexR32/Bracket/blob/f2089bcfbb198f84a7ba5cc8287d0ecf662cba6a/BracketV34.lua#L356)

https://github.com/user-attachments/assets/c93d4609-bf3f-450d-b844-ba337dba3cc7

**Comment by AlexR32** [comment]
Thanks for the bug reports, everything is fixed in https://github.com/AlexR32/Bracket/commit/aaa7e1dc0a99bd67efef7f78133fab3e57352ea1
