### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by NTFSquad** [AlexR32/Bracket#6]
> Alex, how have you been? Anyway, let me get to the point.

### **Stacking Elements More Than Twice**

For example, color pickers!

```lua
--// Currently, I have to predefine the toggle to use two color pickers without stacking:

local Toggle = Toggle:Section({Name = "Health Bar"})

Toggle:Colorpicker({Flag = "High Health Color", Value = {0, 1, 1, 0, false}})
Toggle:Colorpicker({Flag = "Low Health Color", Value = {0.333, 1, 1, 0, false}})

--// What I would like to be able to do:

Toggle:Section({Name = "Health Bar"}):Colorpicker({Flag = "High Health Color", Value = {0, 1, 1, 0, false}}):Colorpicker({Flag = "Low Health Color", Value = {0.333, 1, 1, 0, false}})
```

### **Tooltips**

```lua
--// Currently, I have to predefine the element to use the tooltip:

local Toggle = Toggle:Section({Name = "Health Bar"})

Toggle:Tooltip("Information")

--// What I would like to be able to do:

Toggle:Section({Name = "Health Bar"}):Tooltip("Information")
```

### **Section Fill Option**

Basically, if enabled, it would automatically push the section down to the bottom of the UI. Let me show you what I mean (editing an image to explain it better).

![image](https://github.com/user-attachments/assets/8cafe5f3-7496-4b61-9717-6f54884fc553)

**Comment by NTFSquad** [comment]
i only noticed v34 dev just now...

**Comment by AlexR32** [comment]
> Stacking Elements More Than Twice

Technically impossible with current functions layout

> Tooltips

I just checked with V34_dev and it works
![proof](https://github.com/user-attachments/assets/f47612ca-6139-427d-a853-a60f0f5d1cf7)

> Section Fill Option

Scrolling through the section will become pointless and expanded section will override others that are after it

Hope I made it clear  
also I gave up on scripting in Roblox

**Comment by NTFSquad** [comment]
Understood, wish you the best
