### ISSUE TITLE
Config System

### ISSUE THREAD

**Issue by NTFSquad** [AlexR32/Bracket#7]
> About a month ago, I noticed that the config system stopped working. That's weird—probably my bad code caused it.

### **I just tested it now, and yes, it's actually broken. (V34, V34_dev)**

To reproduce the problem, just try loading a config.

```lua
--// I am using your premade config section here. Give it a try:

local Bracket = loadstring(game:HttpGet("https://raw.githubusercontent.com/AlexR32/Bracket/refs/heads/main/BracketV34_dev.lua"))()

local Window = Bracket:Window()

local Tab = Window:Tab({Name = "Tab"}) do
    Tab:AddConfigSection("Example", nil)
end
```

![image](https://github.com/user-attachments/assets/6ea42660-4ea2-4078-9e05-6b56e9dd5aa3)
![image](https://github.com/user-attachments/assets/e3f261b8-39dc-48d4-92a2-4de4ae7f0c31)

**Comment by AlexR32** [comment]
I dont really know whats the problem, it was working 'back then'

**Comment by NTFSquad** [comment]
**Figured out why config system wasn't working**

by adding dis line before the reading

```lua
print(`{FolderName}\\Configs\\{Name}.json`)
```

and printing out the result i get dis.

![image](https://github.com/user-attachments/assets/d9305b9f-6f34-4ecc-ab00-3ab5c75317f9)

gotta be honest no idea how that happaned

**Comment by NTFSquad** [comment]
**A Big Issue**

This is the biggest problem I’ve seen so far. Basically, after each UI element, there's a space afterward, right? 

But every element *except* the dropdown (when **HideName** is off) has a space that’s too small! Here’s what I mean:

1. **Spacing Issue:**  
   After each UI element, there’s usually some space, like here:
   ![Example 1](https://github.com/user-attachments/assets/37bc92dd-ca10-4798-9189-4b9c31f6f99c)

2. **Dropdown with HideName Off:**  
   With **HideName** off, the space after is too small:
   ![Example 2](https://github.com/user-attachments/assets/bc187d9d-acab-434c-8e6b-3539e4194e17)

3. **Dropdown with HideName On:**  
   But with **HideName** on, it’s spaced right:
   ![Example 3](https://github.com/user-attachments/assets/3ea98c2b-1e19-4dd1-b3a9-8180dd2f414f)
   
Please make it a bit larger

chatgpt was 100% not used to fix mistakes

**Comment by NTFSquad** [comment]
**V34_dev**

If you haven’t completely given up on finishing `v34_dev`, I’ve got some questions—or maybe requests?

I’m thinking of a *MultiSection* feature, where multiple sections are grouped in a switchable interface, as shown here:

![MultiSection Example 1](https://github.com/user-attachments/assets/a32a91c3-6e22-4715-9ad8-c0de3b429ad9)  
![MultiSection Example 2](https://github.com/user-attachments/assets/d43fd7e4-7384-46da-9994-53193406de1f)

**Usage Example**:
Here's what it might look like in use:

```lua
local Enemies, Friendlies, Local = Tab:MultiSection({Sections = {"Enemies", "Friendlies", "Local"}})
```

chatgpt was 100% not used to fix mistakes
